### ISSUE TITLE
Implementing all the routers (Theme Router, Project Router)

### ISSUE THREAD

**Issue by rmifka** [2324-3bhif-teaching/StaticSiteGenerator#12]
This contains adding the Keycloak package aswell!
Estimated Time: 13 hours

**Comment by LukasPerger** [comment]
Themes Router: 

- Alle Themes können geholt werden. 
- Alle Themes eines Users können geholt werden. 
- Ein Theme kann mit dem User und dem Themenamen geholt werden. 
- Es können Themes von einem User mit einem Themenamen erstellt werden. 
- Man kann ein Theme mit Usernamen und Themenamen überschreiben. 
- Es ist das Löschen eines Themes mit dem Usernamen und Themenamen möglich.

Project Router: 

- Es können alle Projekte eines Users abgefragt werden. 
- Es kann genau ein Projekt mit einem Usernamen und dem Projektnamen geholt werden. 
- Es kann ein Projekt mit dem Usernamen und dem Projektnamen erstellt werden. 
- Es kann ein Projekt mit dem User und dem Namen überschrieben werden. 
- Ein Projekt kann mit dem Usernamen und dem Projektnamen gelöscht werden.

User Router: KeyCloak?
