### ISSUE TITLE
Implementing a AsciiDoc to HTML Parser

### ISSUE THREAD

**Issue by rmifka** [2324-3bhif-teaching/StaticSiteGenerator#14]
A markdown parser that converts Markdown Elements to Html Elements. This step does **NOT** contain the theme generation. This is done in an earlier step!
Estimated Time: 10 Hours

**Comment by LukasPerger** [comment]
MD zu HTML Praser:

Headings:

- `# Heading` zu `<h1>Heading</h1>`

Bold:

- `**Bold**` zu `<b>Bold</b>`
- HTML-Tag und CSS-Klassenname müssen nicht genau so heißen

Italic:

- `_italic_` zu `<i>Italic</i>`
- HTML-Tag und CSS-Klassenname müssen nicht genau so heißen

Blockquote:

- `> Blockquote` zu `<blockquote>Blockquote</blockquote>`
- Die Formatierung des HTML-Tags kann variieren

**Comment by rmifka** [comment]
The Team has decided against implementing our own AsciiDoc Parser. We have now used [asciidoctor,js](https://github.com/asciidoctor/asciidoctor.js/)
