### ISSUE TITLE
Generate Static Website using the Routes

### ISSUE THREAD

**Issue by rmifka** [2324-3bhif-teaching/StaticSiteGenerator#15]
Ship a zip containing all the things you need for the website. It should be hostable as is!
Estimated Time: 2 Hours

**Comment by LukasPerger** [comment]
Job:

- Parser wird bentzt um die Webseite zu generieren
- Wenn die ganze Seite generiert werden soll wird noch gezippt 
- Projekt Router kann benutzt, werden um die Preview Webseite und ganze Webseite zu generieren
